### ISSUE TITLE
Solve union issue with io-ts

### ISSUE THREAD

**Issue by Ahryman40k** [Ahryman40k/typescript-fhir-types#2]
PASS  src/__tests__/account_coverage.spec.ts
 PASS  src/__tests__/tryout.spec.ts
 PASS  src/__tests__/account_guarantor.spec.ts (17.176s)
 FAIL  src/__tests__/account.spec.ts
  ● Test suite failed to run

    TypeError: Cannot read property 'name' of undefined

      146 | import * as t from 'io-ts';
      147 | 
    > 148 | export const RTTI_ResourceList = t.union([
          |                                    ^
      149 |     RTTI_Account,
      150 |     RTTI_ActivityDefinition,
      151 |     RTTI_AdverseEvent,

      at node_modules/io-ts/lib/index.js:764:59
          at Array.map (<anonymous>)
      at getUnionName (node_modules/io-ts/lib/index.js:764:25)
      at Object.<anonymous>.exports.union (node_modules/io-ts/lib/index.js:770:35)
      at Object.<anonymous> (src/Union/RTTI_ResourceList.ts:148:36)
      at Object.<anonymous> (src/Resource/RTTI_Account.ts:6:1)
      at Object.<anonymous> (src/__tests__/account.spec.ts:1:1)

Test Suites: 1 failed, 3 passed, 4 total
Tests:       5 passed, 5 total
Snapshots:   0 total
Time:        22.055s

**Comment by Ahryman40k** [comment]
When solved, I may make resources 'exact'

**Comment by Ahryman40k** [comment]
Solved, 

hahaha, I didn't make a recursion of union as all types do !

**Comment by Ahryman40k** [comment]
Fixed in 4.0.4
